### ISSUE TITLE
L transformation name

### ISSUE THREAD

**Issue by marcfedorow** [rvkrypto/rvkrypto-gost#1]
Hi @mjosaarinen.
You are doing a great job and it is very well done.
Just to be academically accurate, the name of [linear transform](https://github.com/rvkrypto/rvkrypto-gost/blob/e9413d8a6b5910bb8817f6b6480727488e4b0a02/rtl/gost32_sbg_lin1.v#L6) is "L transformation" with the capital L.
Here is the quote from [standard](https://eprint.iacr.org/2013/556.pdf) which you can find on the 6th page:
```
The L transformation is based on a linear transformation l, which is given
by the right multiplication by a fixed 64×64 matrix over the field F2
```

So I suggest to use the capital L for this linear transform to not mix up things even further.
Once again -- everything is great and this is a very minor suggestion.

**Comment by mjosaarinen** [comment]
Yeah, it's useful to have the capital L to refer to the major L component step of the LPS transform. Changed in: https://github.com/rvkrypto/rvkrypto-gost/commit/b9551b410594d14349a8549dfa2974be8059bb86
